name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Go Coverage
      uses: gwatts/go-coverage-action@v2.0.0
      with:
        coverage-threshold: 80
        cover-pkg: ./...